# Generated by Django 4.1.5 on 2023-01-31 17:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.CharField(blank=True, default='', max_length=100)),
                ('bssid', models.CharField(blank=True, default='', max_length=100)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.IntegerField(null=True)),
                ('rates', models.CharField(blank=True, default='', max_length=100)),
                ('rssi', models.IntegerField(null=True)),
                ('security', models.CharField(blank=True, default='', max_length=100)),
                ('ssid', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.IntegerField(null=True)),
                ('vendor', models.CharField(blank=True, default='', max_length=100)),
                ('width', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
